SELECT
    FANUMFACT,
    NUMCLIENT,
    NUMDOSSIER,
    REFCLIENT,
    TOTREVERTTC,
    TOTDISPO,
    TOTRGLT,
    FADATEDIT,
    FADATEECH,
    TOTMTHONO,
    FAMTTVA,
    HTREGLCLIENT,
    HTREGDISPO,
    MTTTC,
    TYPFACT,
    TRNUMMVT,
    substring(FAMODREG,1 , 3) as FAMODREG,
    substring(FACONDPAIE,1 , 250) as FACONDPAIE,
    FADATECREA
FROM FACTURE
WHERE MTTTC <> 0;