SELECT 
    HICLEUNIK,
    SUBSTRING(NUMREF, 1, 20) AS NUMREF,
    DATHISTO,
    SUBSTRING(LIBHISTO, 1, 100) AS LIBHISTO,
    SUBSTRING(COMMHISTO, 1, 500) AS COMMHISTO,
    SUBSTRING(NREDACT, 1, 50) AS NREDACT,
    SUBSTRING(HINUMCLI, 1, 20) AS HINUMCLI
FROM HISTO H 
    INNER JOIN DEBITEUR D 
    ON D.NUMDEB = H.NUMREF 
WHERE D.ETATDOSS = '00001';