CREATE TABLE AVOIRS (
    IDAVOIRS INT PRIMARY KEY,
    NUMDEB VARCHAR(20),
    NUMCLI VARCHAR(20),
    AVLIBELLE VARCHAR(255),
    AVDATE DATE,
    AVDATESAISIE DATE,
    AVREFERENCE VARCHAR(50),
    AVMONTANT DECIMAL(15,2)
);