CREATE TABLE CLIENT (
    NUMCLI VARCHAR(20) PRIMARY KEY,
    SIRENCLI VARCHAR(9),
    ALPHACLI VARCHAR(255),
    NUMCOMM VARCHAR(20),
    NUMINT VARCHAR(20),
    NUMREDA VARCHAR(20),
    NUMCORR VARCHAR(20),
    SOCCLI VARCHAR(255),
    QUALCLI VARCHAR(50),
    NOMCLI VARCHAR(255),
    PRENOMCLI VARCHAR(255),
    JURCLI VARCHAR(50),
    ADRCLI1 VARCHAR(255),
    ADRCLI2 VARCHAR(255),
    ADRCLI3 VARCHAR(255),
    CPCLI VARCHAR(10),
    VILLECLI VARCHAR(100),
    PAYSCLI VARCHAR(50),
    DTINSCLI DATE,
    TELCLI1 VARCHAR(20),
    TELCLI2 VARCHAR(20),
    FAXCLI VARCHAR(20),
    WEBCLI VARCHAR(255)
);
CREATE INDEX numreda_ix ON client (NUMREDA);
CREATE INDEX numint_ix  ON client (NUMINT);
CREATE INDEX numcomm_ix ON client (NUMCOMM);
