CREATE TABLE DEBFICHE (
    DFCLEUNIK BIGINT,
    DFQUAL VARCHAR(10),
    DFNOM VARCHAR(100),
    DFPRENOM VARCHAR(100),
    DFNOMJF VARCHAR(100),
    DFDATENAIS DATE,
    DFLIEUNAIS VARCHAR(100),
    DFSIREN VARCHAR(20),
    DFCP VARCHAR(20),
    DFVILLE VARCHAR(50),
    DFPAYS VARCHAR(50),
    DFPROF VARCHAR(100),
    DFENSEIGNE VARCHAR(100),
    DFFORMJ VARCHAR(50)
);
