CREATE TABLE DEBITEUR (
    NUMDEB VARCHAR(20),
    NUMCLI VARCHAR(20),
    ALPHADEB VARCHAR(100),
    NUMINT VARCHAR(20),
    NUMREDA VARCHAR(20),
    NUMCAUT VARCHAR(20),
    REFCLI VARCHAR(100),
    JURDEB VARCHAR(50),
    CPDEB VARCHAR(20),
    VILLEDEB VARCHAR(50),
    PAYSDEB VARCHAR(50),
    DTINSDEB DATE,
    DATDOSS DATE,
    ETATDOSS VARCHAR(10),
    SOUSETATDOSS VARCHAR(10),
    SIRENDEB  VARCHAR(10),
    DATETAT DATE,
    DatDernEnv DATE,
    DatProcEnv DATE,
    DBTOTALDU DECIMAL(10, 2),
    DBTOTALPR DECIMAL(10, 2),
    DBFRAISPR DECIMAL(10, 2),
    DBFRAISCAB DECIMAL(10, 2),
    DBTOTALREG DECIMAL(10, 2),
    DBRESTANTDU DECIMAL(10, 2),
    DBRESTANTPR DECIMAL(10, 2),
    DBRESTANTFRAISPR DECIMAL(10, 2),
    DBANCIENNETE int,
    REMDEB VARCHAR(1000)
);
CREATE INDEX numcli_ix ON debiteur (NUMCLI);
CREATE INDEX etatdos_ix ON debiteur (ETATDOSS);
CREATE INDEX setados_ix ON debiteur (SOUSETATDOSS);
