CREATE TABLE HISTO (
    HICLEUNIK INT NOT NULL,
    NUMREF VARCHAR(20) not null,
    DATHISTO DATE not null,
    LIBHISTO VARCHAR(150) not null,
    COMMHISTO VARCHAR(500),
    NREDACT VARCHAR(50),
    HINUMCLI VARCHAR(20)
);