CREATE TABLE PRINC (
    PRCLEUNIK INT PRIMARY KEY,
    NUMDEB VARCHAR(20) NOT NULL,
    TYPPR CHAR(1) NOT NULL,
    ORDRE INT NOT NULL,
    NUMCLI VARCHAR(20) NOT NULL,
    LIBELLE VARCHAR(255),
    PRINCINIT DECIMAL(15,2) NOT NULL,
    PRINC DECIMAL(15,2) NOT NULL,
    DATEPR DATE,
    DATECHPR DATE NOT NULL,
    TXINTERET DECIMAL(5,2) NOT NULL,
    TXCP DECIMAL(5,2) NOT NULL,
    TXDI DECIMAL(5,2) NOT NULL,
    HTREGLMT DECIMAL(15,2) NOT NULL,
    PRNUFRAIS VARCHAR(20),
    PRREF VARCHAR(50)
    );